### ISSUE TITLE
how can I enable username/password auth ?

### ISSUE THREAD

**Issue by fallshuang** [theia-ide/theia-apps#167]
I start theia in docker ,  how can I enable username/password auth ?

**Comment by marcdumais-work** [comment]
Hi @fallshuang ,

Since Theia applications can be used natively (i.e. run directly on one's computer, where the user has already authenticated), we do not consider user authentication to be in-scope, but rather as something to be dealt-with outside of Theia, if/when required. For example workspace servers that integrate Theia, such as Eclipse Che and Gitpod, will take care of this.

**Comment by land007** [comment]
If you want to use your username and password to enhance your security, you can use the following command, where the password needs to be filled with MD5.

```bash
docker rm -f theia; docker run -it --privileged -p 15050:5050 --expose 9229 -p 19229:9229 -v "$(pwd):/home/project:cached" -e "username=land007" -e "password=fcea920f7412b5da7be0cf42b8c93759" --name theia land007/theia:latest
```
Please visit http://docker_ip:15050/ and log in with username land007 and password 1234567

**Comment by marcdumais-work** [comment]
Thanks @land007 : this seems like your suggestion is a simple way to enable some form of authentication.

**Comment by Jayuda** [comment]
Sorry @land007, i have try your suggestions but not working. 
Any update ?

**Comment by land007** [comment]
@Jayuda You may be mapping directory error, please try the following command
···bash
docker run -it --privileged -p 15050:5050 --expose 9229 -p 19229:9229 -e "username=land007" -e "password=fcea920f7412b5da7be0cf42b8c93759" --name theia land007/theia:latest
···

**Comment by DilLip-Chowdary-Codes** [comment]
> I start theia in docker , how can I enable username/password auth ?

https://github.com/DilLip-Chowdary-Codes/Theia_Authentication_Integrated

**Comment by land007** [comment]
You can also use the original mirror to do https and username password
```
version: "2.1"
networks:
  internal_network:
services:
  theia:
    restart: always
    networks:
      - internal_network
    image: theiaide/theia:latest
    container_name: theia
    volumes:
      - ./project:/home/project:cached
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "3"
    expose:
      - "3000"
  theia_http-proxy:
    restart: always
    networks:
      - internal_network
    links:
      - gantt
    image: land007/http-proxy:latest
    container_name: theia_http-proxy
    volumes:
      - ./cert/www.****.com_chain.crt:/node/cert/www.****.com_chain.crt
      - ./cert/www.****.com_key.key:/node/cert/www.****.com_key.key
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "3"
    environment:
      - "password=fcea920f7412b5da7be0cf42b8c93759"
      - "DOMAIN_NAME=www.****.com"
      - "http_proxy_domains="
      - "http_proxy_paths=/"
      - "http_proxy_hosts=theia"
      - "http_proxy_ports=3000"
      - "http_proxy_pretends=false"
      - "ws_proxy_domains="
      - "ws_proxy_paths=/"
      - "ws_proxy_hosts=theia"
      - "ws_proxy_ports=3000"
    expose:
      - "20022"
      - "8443"
      - "443"
      - "80"
    ports:
      - "5050:443"
```
