### ISSUE TITLE
Add theia-docker-full to travis

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia-apps#25]

**Comment by marcdumais-work** [comment]
Cool. 

We have noticed a few times that the Ubuntu APT repository that we use for LLVM/clangd has relatively frequent, momentary, stability issues, that can cause the image build to fail. Do we want to fail the overall build, in this case?

**Comment by hexa00** [comment]
Yes it would be better to have a different travis config just for that one.

**Comment by akosyakov** [comment]
You should be able to mark such jobs with [allow_failures](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail), something like:
```yaml
matrix:
  allow_faiures:
    - env: NPM_TAG=latest IMAGE_NAME=theia-full
```
